# Generated by Django 4.2 on 2025-02-22 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_projects_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='nome',
        ),
        migrations.AddField(
            model_name='projects',
            name='link_project',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='projects',
            name='projetc_img',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='projects',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='projects',
            name='title_back',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='projects',
            name='tools',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
