# Generated by Django 4.2 on 2025-03-06 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_projects_nome_projects_link_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='projetc_img',
            field=models.ImageField(upload_to='projects/'),
        ),
    ]
