# Generated by Django 4.2 on 2025-03-15 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_senha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='projetc_img',
            field=models.ImageField(blank=True, null=True, upload_to='upload_image'),
        ),
    ]
