# Generated by Django 4.2 on 2025-03-15 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_projects_projetc_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='projetc_img',
            field=models.ImageField(upload_to='projects/'),
        ),
    ]
