# Generated by Django 4.2 on 2025-03-15 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_projects_projetc_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='projetc_img_binary',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='projetc_img',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
    ]
